baseURL = "https://seppi91.github.io/estherkarcher.de/" 
canonifyurls = true # remove after custom domain
languageCode = "en-us" 
theme = "estherkarcher" 
title = "Esther Karcher | Architekturbüro in Karlsruhe Architekt" 
[menu]
[[menu.main]]
identifier = "about"
name = "Büro"
url = "/about/"
weight = 1
[[menu.main]]
name = "Projekte"
url = "/"
weight = 2
[[menu.main]]
name = "Kontakt"
url = "/contact/"
weight = 3

[params]
author = "Esther Karcher"
description = "Esther Karcher, Architektin aus Karlsruhe: Funktionalität und Wirtschaftlichkeit sind die Basis für gute Architektur – jedoch nie deren alleiniges Ziel."
logo = "https://www.estherkarcher.de/wp-content/uploads/2017/11/logo2.png"
[params.css]
head = [
]
[params.javascript]
bottom = [
]

[markup.goldmark.renderer]
hardWraps = true
